"use strict";
/**
 * Generates src/signals.json — rotating pull quotes / short verse for the interstitial.
 * Run: node scripts/build-signals.cjs
 */
const fs = require("fs");
const path = require("path");

/** @param {string} by @param {string} a @param {string} [b] */
function pack(by, a, b) {
  return { lines: b ? [a, b] : [a, ""], by };
}

const DATA = [
  pack("Ernest Shackleton", "Men wanted for hazardous journey.", "Safe return doubtful. Honour in case of success."),
  pack("Ernest Shackleton", "Optimism is true moral courage.", ""),
  pack("Ernest Shackleton", "Difficulties are just things to overcome, after all.", ""),
  pack("Ernest Shackleton", "By endurance we conquer.", ""),
  pack("Ernest Shackleton", "Superhuman effort isn't worth a damn unless it achieves results.", ""),
  pack("Ernest Shackleton", "If you're a leader, a fellow that other fellows look to,", "you've got to keep going."),
  pack("Roald Amundsen", "Victory awaits him who has everything in order —", "luck, people call it."),
  pack("Roald Amundsen", "We see many fine sunsets if we are still on the march.", ""),
  pack("Franklin D. Roosevelt", "The only thing we have to fear is fear itself.", ""),
  pack("Theodore Roosevelt", "The credit belongs to the man who is actually in the arena,", "whose face is marred by dust and sweat and blood."),
  pack("Theodore Roosevelt", "Do what you can, with what you have, where you are.", ""),
  pack("Theodore Roosevelt", "Far better it is to dare mighty things,", "than to rank with those timid spirits who neither enjoy much nor suffer much."),
  pack("David Livingstone", "I am prepared to go anywhere,", "provided it be forward."),
  pack("Henry Stanley", "Dr. Livingstone, I presume?", ""),
  pack("T. E. Lawrence", "All men dream, but not equally.", "Those who dream by night wake to the day."),
  pack("Matthew Henson", "There can be no conquest to the man who dwells in the frozen bosom of fear.", ""),
  pack("Amelia Earhart", "The most difficult thing is the decision to act;", "the rest is merely tenacity."),
  pack("Amelia Earhart", "Adventure is worthwhile in itself.", ""),
  pack("John Wesley Powell", "We have an unknown distance yet to run, an unknown river yet to explore.", ""),
  pack("Neil Armstrong", "That's one small step for man,", "one giant leap for mankind."),
  pack("Marie Curie", "Nothing in life is to be feared, it is only to be understood.", "Now is the time to understand more."),
  pack("Thomas Edison", "Genius is one percent inspiration,", "ninety-nine percent perspiration."),
  pack("Thomas Edison", "I have not failed.", "I've just found 10,000 ways that won't work."),
  pack("Henry Ford", "Whether you think you can or you think you can't,", "you're right."),
  pack("Andrew Carnegie", "People who are unable to motivate themselves must be content with mediocrity,", "no matter how impressive their other talents."),
  pack("John D. Rockefeller", "I would rather earn 1% of 100 people's efforts", "than 100% of my own efforts."),
  pack("Otto von Bismarck", "Fools learn from experience.", "I prefer to learn from the fools' experiences."),
  pack("Winston Churchill", "Success is not final, failure is not fatal:", "it is the courage to continue that counts."),
  pack("Winston Churchill", "If you're going through hell,", "keep going."),
  pack("Winston Churchill", "Never give in,", "except to convictions of honour and good sense."),
  pack("George Washington", "It is better to offer no excuse than a bad one.", ""),
  pack("Abraham Lincoln", "Nearly all men can stand adversity,", "but if you want to test a man's character, give him power."),
  pack("Abraham Lincoln", "The best thing about the future", "is that it comes one day at a time."),
  pack("Frederick Douglass", "If there is no struggle, there is no progress.", ""),
  pack("Susan B. Anthony", "Failure is impossible.", ""),
  pack("Booker T. Washington", "Success is to be measured not so much by the position one has reached in life", "as by the obstacles which one has overcome."),
  pack("John Muir", "The mountains are calling,", "and I must go."),
  pack("Ralph Waldo Emerson", "Trust thyself:", "every heart vibrates to that iron string."),
  pack("Ralph Waldo Emerson", "A foolish consistency is the hobgoblin of little minds.", ""),
  pack("Henry David Thoreau", "Go confidently in the direction of your dreams.", "Live the life you have imagined."),
  pack("Henry David Thoreau", "The mass of men lead lives of quiet desperation.", ""),
  pack("Henry David Thoreau", "If one advances confidently in the direction of his dreams,", "and endeavors to live the life he has imagined, he will meet with a success unexpected in common hours."),
  pack("Walt Whitman", "I celebrate myself, and sing myself,", "And what I assume you shall assume."),
  pack("Walt Whitman", "Keep your face always toward the sunshine—", "and shadows will fall behind you."),
  pack("Walt Whitman", "Re-examine all you have been told.", "Dismiss whatever insults your own soul."),
  pack("Emily Dickinson", "Hope is the thing with feathers", "That perches in the soul."),
  pack("Emily Dickinson", "Forever is composed of nows.", ""),
  pack("Emily Dickinson", "The soul should always stand ajar", "That freezing persons may enter in."),
  pack("Emily Dickinson", "Because I could not stop for Death —", "He kindly stopped for me —"),
  pack("Emily Dickinson", "I'm Nobody! Who are you?", "Are you — Nobody — too?"),
  pack("Edgar Allan Poe", "All that we see or seem", "Is but a dream within a dream."),
  pack("Edgar Allan Poe", "I became insane, with long intervals", "of horrible sanity."),
  pack("Edgar Allan Poe", "Those who dream by day are cognizant of many things", "which escape those who dream only by night."),
  pack("Henry Wadsworth Longfellow", "Lives of great men all remind us", "We can make our lives sublime,"),
  pack("Henry Wadsworth Longfellow", "The heights by great men reached and kept", "Were not attained by sudden flight,"),
  pack("Henry Wadsworth Longfellow", "Perseverance is a great element of success.", "If you only knock long enough at the gate, you are sure to wake up somebody."),
  pack("William Shakespeare", "To thine own self be true,", "And it must follow, as the night the day,"),
  pack("William Shakespeare", "We are such stuff as dreams are made on,", "and our little life is rounded with a sleep."),
  pack("William Shakespeare", "The fool doth think he is wise,", "But the wise man knows himself to be a fool."),
  pack("William Shakespeare", "Cowards die many times before their deaths;", "The valiant never taste of death but once."),
  pack("William Shakespeare", "Brevity is the soul of wit.", ""),
  pack("William Blake", "Tyger Tyger, burning bright,", "In the forests of the night;"),
  pack("William Blake", "To see a World in a Grain of Sand", "And a Heaven in a Wild Flower,"),
  pack("William Blake", "What is now proved was once only imagined.", ""),
  pack("John Keats", "A thing of beauty is a joy forever:", "Its loveliness increases; it will never"),
  pack("John Keats", "Beauty is truth, truth beauty,—that is all", "Ye know on earth, and all ye need to know."),
  pack("Percy Bysshe Shelley", "If Winter comes, can Spring be far behind?", ""),
  pack("Percy Bysshe Shelley", "O wild West Wind, thou breath of Autumn's being,", "Thou from whose unseen presence the leaves dead"),
  pack("William Wordsworth", "The world is too much with us; late and soon,", "Getting and spending, we lay waste our powers;"),
  pack("William Wordsworth", "I wandered lonely as a cloud", "That floats on high o'er vales and hills,"),
  pack("Samuel Taylor Coleridge", "Water, water, everywhere,", "Nor any drop to drink."),
  pack("Samuel Taylor Coleridge", "What is an epigram? A dwarfish whole,", "Its body brevity, and wit its soul."),
  pack("Alfred, Lord Tennyson", "'Tis better to have loved and lost", "Than never to have loved at all."),
  pack("Alfred, Lord Tennyson", "To strive, to seek, to find,", "and not to yield."),
  pack("Elizabeth Barrett Browning", "How do I love thee? Let me count the ways.", "I love thee to the depth and breadth and height"),
  pack("Robert Browning", "Grow old along with me!", "The best is yet to be,"),
  pack("Lord Byron", "She walks in beauty, like the night", "Of cloudless climes and starry skies;"),
  pack("John Milton", "Awake, arise, or be forever fall'n.", ""),
  pack("John Milton", "The mind is its own place, and in itself", "Can make a Heav'n of Hell, a Hell of Heav'n."),
  pack("Alexander Pope", "A little learning is a dangerous thing;", "drink deep, or taste not the Pierian spring."),
  pack("Alexander Pope", "Fools rush in where angels fear to tread.", ""),
  pack("Oliver Goldsmith", "Where wealth accumulates, and men decay.", ""),
  pack("William Cowper", "Variety's the very spice of life", "That gives it all its flavor."),
  pack("Edward FitzGerald (trans.)", "The Moving Finger writes; and, having writ,", "Moves on: nor all your Piety nor Wit"),
  pack("W. E. Henley", "I am the master of my fate,", "I am the captain of my soul."),
  pack("Paul Laurence Dunbar", "I know why the caged bird sings,", "ah me,"),
  pack("John McCrae", "In Flanders fields the poppies blow", "Between the crosses, row on row,"),
  pack("Rudyard Kipling", "If you can keep your head when all about you", "Are losing theirs and blaming it on you,"),
  pack("Rudyard Kipling", "The strength of the Pack is the Wolf,", "and the strength of the Wolf is the Pack."),
  pack("Robert Service", "There's a race of men that don't fit in,", "A race that can't stay still;"),
  pack("Edna St. Vincent Millay", "My candle burns at both ends;", "It will not last the night;"),
  pack("Sara Teasdale", "There will be rest, and sure stars shining", "Over the roof-tops crowned with snow,"),
  pack("A. E. Housman", "Loveliest of trees, the cherry now", "Is hung with bloom along the bough,"),
  pack("Robert Louis Stevenson", "Don't judge each day by the harvest you reap", "but by the seeds that you plant."),
  pack(
    "Charlotte Brontë",
    "I would always rather be happy than dignified.",
    "",
  ),
  pack("Leo Tolstoy (trans.)", "Everyone thinks of changing the world,", "but no one thinks of changing himself."),
  pack("Victor Hugo (trans.)", "There is nothing more powerful than an idea whose time has come.", ""),
  pack("Friedrich Nietzsche (trans.)", "He who has a why to live can bear almost any how.", ""),
  pack("Johann Wolfgang von Goethe (trans.)", "What is not started today is never finished tomorrow.", ""),
  pack("Seneca (trans.)", "Luck is what happens when preparation meets opportunity.", ""),
  pack("Marcus Aurelius (trans.)", "You have power over your mind — not outside events.", "Realize this, and you will find strength."),
  pack("Epictetus (trans.)", "No man is free who is not master of himself.", ""),
  pack("Epictetus (trans.)", "It's not what happens to you,", "but how you react to it that matters."),
  pack("Confucius (trans.)", "It does not matter how slowly you go", "as long as you do not stop."),
  pack("Sun Tzu (trans.)", "In the midst of chaos, there is also opportunity.", ""),
  pack("Jeff Bezos", "It is always Day 1.", ""),
  pack("Steve Jobs", "Real artists ship.", ""),
  pack("Steve Jobs", "Stay hungry. Stay foolish.", ""),
  pack("Steve Jobs", "Design is not just what it looks like.", "Design is how it works."),
  pack("Bill Gates", "Your most unhappy customers", "are your greatest source of learning."),
  pack("Andy Grove", "Only the paranoid survive.", ""),
  pack("Larry Ellison", "When you innovate, you've got to be prepared for people telling you you're nuts.", ""),
  pack("Reid Hoffman", "If you are not embarrassed by the first version of your product,", "you've launched too late."),
  pack("Marc Andreessen", "Software is eating the world.", ""),
  pack("Paul Graham / Y Combinator", "Make something people want.", ""),
  pack("Jim Collins", "Good is the enemy of great.", ""),
  pack("Brian Chesky", "If we tried to think of a good idea,", "we wouldn't have been able to think of Airbnb."),
  pack("Drew Houston", "Don't worry about failure;", "you only have to be right once."),
  pack("Sheryl Sandberg", "Done is better than perfect.", ""),
  pack("Satya Nadella", "Our industry does not respect tradition.", "It only respects innovation."),
  pack("Jensen Huang", "There are no shortcuts to building a company that lasts.", ""),
  pack("Mary Barra", "Do every job you're in like you're going to do it for the rest of your life,", "and demonstrate that ownership of it."),
  pack("Estée Lauder", "I never dreamed about success.", "I worked for it."),
  pack("Madame C. J. Walker", "Don't sit down and wait for the opportunities to come.", "Get up and make them."),
  pack("Grace Hopper", "A ship in port is safe,", "but that is not what ships are built for."),
  pack("Isaac Newton", "If I have seen further it is by standing on the shoulders of Giants.", ""),
  pack("Michael Faraday", "Nothing is too wonderful to be true", "if it be consistent with the laws of nature."),
  pack("Charles Darwin", "It is not the strongest of the species that survive,", "nor the most intelligent, but the one most responsive to change."),
  pack("Claude Bernard", "Art is I; science is we.", ""),
  pack("Louis Pasteur", "Fortune favors the prepared mind.", ""),
  pack("Richard Feynman", "The first principle is that you must not fool yourself", "and you are the easiest person to fool."),
  pack("James Clerk Maxwell", "The special theory of relativity owes its origins to Maxwell's equations.", ""),
  pack("Louis Brandeis", "If we desire respect for the law, we must first make the law respectable.", ""),
  pack("Eleanor Roosevelt", "Do one thing every day that scares you.", ""),
  pack("Maya Angelou", "You may encounter many defeats, but you must not be defeated.", ""),
  pack("Maya Angelou", "Nothing will work unless you do.", ""),
  pack(
    "Martin Luther King Jr.",
    "Faith is taking the first step even when you don't see the whole staircase.",
    "",
  ),
  pack("Martin Luther King Jr.", "The time is always right to do what is right.", ""),
  pack("Helen Keller", "Life is either a daring adventure", "or nothing at all."),
  pack("George Eliot", "It is never too late to be what you might have been.", ""),
  pack("Harriet Beecher Stowe", "Never give up, for that is just the place and time", "that the tide will turn."),
  pack("Sojourner Truth", "If the first woman God ever made was strong enough to turn the world upside down,", "these women together ought to be able to turn it right side up again."),
  pack("Oscar Wilde", "We are all in the gutter,", "but some of us are looking at the stars."),
  pack("Oscar Wilde", "Experience is simply the name", "we give our mistakes."),
  pack("Mark Twain", "The secret of getting ahead is getting started.", ""),
  pack("Mark Twain", "Courage is resistance to fear,", "mastery of fear — not absence of fear."),
  pack("Antoine de Saint-Exupéry (trans.)", "Perfection is achieved, not when there is nothing more to add,", "but when there is nothing left to take away."),
  pack("Antoine de Saint-Exupéry (trans.)", "A goal without a plan is just a wish.", ""),
  pack("Antoine de Saint-Exupéry (trans.)", "If you want to build a ship, don't drum up people to gather wood,", "divide the work, and give orders. Teach them to yearn for the endless sea."),
  pack("Voltaire (trans.)", "Judge a man by his questions rather than by his answers.", ""),
  pack("Voltaire (trans.)", "Perfect is the enemy of good.", ""),
  pack("René Descartes (trans.)", "Except our own thoughts, there is nothing absolutely in our power.", ""),
  pack("Blaise Pascal (trans.)", "The heart has its reasons that reason knows nothing of.", ""),
  pack("Benjamin Franklin", "Lost time is never found again.", ""),
  pack("Benjamin Franklin", "Energy and persistence conquer all things.", ""),
  pack("Michelangelo", "The greater danger for most of us lies not in setting our aim too high", "and falling short, but in setting our aim too low, and achieving our mark."),
  pack("Leonardo da Vinci", "Learning never exhausts the mind.", ""),
  pack("Leonardo da Vinci", "Simplicity is the ultimate sophistication.", ""),
  pack("Albert Einstein", "In the middle of difficulty lies opportunity.", ""),
  pack("Albert Einstein", "Life is like riding a bicycle.", "To keep your balance, you must keep moving."),
  pack("Albert Einstein", "Imagination is more important than knowledge.", ""),
  pack("General George S. Patton", "Accept the challenges so that you may feel the exhilaration of victory.", ""),
  pack("Dwight D. Eisenhower", "What counts is not necessarily the size of the dog in the fight;", "it's the size of the fight in the dog."),
  pack("Douglas MacArthur", "There is no substitute for victory.", ""),
  pack("Helen Keller", "Alone we can do so little;", "together we can do so much."),
  pack("Helen Keller", "Optimism is the faith that leads to achievement.", ""),
];

function dedupe(entries) {
  const seen = new Set();
  const out = [];
  for (const e of entries) {
    const k = `${e.by}::${e.lines[0]}::${e.lines[1] ?? ""}`;
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(e);
  }
  return out;
}

const out = dedupe(DATA);
const outPath = path.join(__dirname, "..", "src", "signals.json");
fs.writeFileSync(outPath, JSON.stringify(out, null, 2) + "\n");
console.log("Wrote", out.length, "signals →", outPath);
